# Generated by Django 2.1.3 on 2019-06-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accomplished', models.DateTimeField(null=True)),
                ('emoployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesmen.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='responsibility',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesmen.Task'),
        ),
        migrations.AddField(
            model_name='employee',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, through='salesmen.Responsibility', to='salesmen.Task'),
        ),
    ]
