# Generated by Django 2.1.3 on 2018-12-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='date_accomplished',
            field=models.DateTimeField(),
        ),
    ]
