# Generated by Django 2.1.3 on 2018-12-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmen', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='salesmen.Task'),
        ),
    ]
